research_task:
  description: >
    Conduct a thorough research about {user_query}. Make sure you find any
    interesting and relevant information from PDF stored locally on {pdf_path}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {user_query}
  agent: pdf_explorer

reporting_task:
  description: >
    Review the context you got from pdf_explorer and use that to create notes/summary
    for {user_query}. Make sure the answer is precise and contains any and all relevant
    information present in the context.
  expected_output: >
    A clear and concise answer for {user_query} with a full information.
    Formatted as markdown without '```'
  agent: pdf_analyst
